import { BUSINESS_MODEL_VALIDATION_PROMPT } from "./business-model";
import { COMPETITIVE_ANALYSIS_PROMPT } from "./competitive-analysis";
import { CUSTOMER_VALIDATION_PROMPT } from "./customer-validation";
import { FINANCIAL_PROJECTIONS_VALIDATION_PROMPT } from "./financial-projections";
import { MARKET_OPPORTUNITY_VALIDATION_PROMPT } from "./market-opportunity";
import { PRODUCT_MARKET_FIT_VALIDATION_PROMPT } from "./product-market-fit";
import { RISK_ANALYSIS_VALIDATION_PROMPT } from "./risk-analysis";
import { TECHNICAL_FEASIBILITY_VALIDATION_PROMPT } from "./technical-feasibility";
import { GO_TO_MARKET_VALIDATION_PROMPT } from "./go-to-market";
import { INVESTMENT_RECOMMENDATION_VALIDATION_PROMPT } from "./investment-recommendation";
import { SAAS_VALIDATION_PROMPT } from "../complete-validation";

export {
  BUSINESS_MODEL_VALIDATION_PROMPT,
  COMPETITIVE_ANALYSIS_PROMPT,
  CUSTOMER_VALIDATION_PROMPT,
  FINANCIAL_PROJECTIONS_VALIDATION_PROMPT,
  MARKET_OPPORTUNITY_VALIDATION_PROMPT,
  PRODUCT_MARKET_FIT_VALIDATION_PROMPT,
  RISK_ANALYSIS_VALIDATION_PROMPT,
  TECHNICAL_FEASIBILITY_VALIDATION_PROMPT,
  GO_TO_MARKET_VALIDATION_PROMPT,
  INVESTMENT_RECOMMENDATION_VALIDATION_PROMPT,
  SAAS_VALIDATION_PROMPT,
};
