interface Env {
  DATABASE_URL: string;
  WEBHOOK_SECRET: string;
  GOOGLE_GENERATIVE_AI_API_KEY: string;

  POLAR_ACCESS_TOKEN: string;
  POLAR_PRICE_STARTER: string;
  POLAR_PRICE_BUSINESS: string;
  POLAR_PRICE_ENTERPRISE: string;


  BETTER_AUTH_SECRET: string;
  BETTER_AUTH_URL: string;

  LIVEBLOCKS_SECRET_KEY: string;
  NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY: string;

  CONVEX_DEPLOYMENT: string;
  NEXT_PUBLIC_CONVEX_URL: string;

}

const env: Env = {
  DATABASE_URL: process.env.DATABASE_URL!,
  WEBHOOK_SECRET: process.env.WEBHOOK_SECRET!,
  GOOGLE_GENERATIVE_AI_API_KEY: process.env.GOOGLE_GENERATIVE_AI_API_KEY!,

  POLAR_ACCESS_TOKEN: process.env.POLAR_ACCESS_TOKEN!,
  POLAR_PRICE_STARTER: process.env.POLAR_PRICE_STARTER!,
  POLAR_PRICE_BUSINESS: process.env.POLAR_PRICE_BUSINESS!,
  POLAR_PRICE_ENTERPRISE: process.env.POLAR_PRICE_ENTERPRISE!,


  BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET!,
  BETTER_AUTH_URL: process.env.BETTER_AUTH_URL!,

  LIVEBLOCKS_SECRET_KEY: process.env.LIVEBLOCKS_SECRET_KEY!,
  NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY: process.env.NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY!,

  CONVEX_DEPLOYMENT: process.env.CONVEX_DEPLOYMENT!,
  NEXT_PUBLIC_CONVEX_URL: process.env.NEXT_PUBLIC_CONVEX_URL!,

};

export default env;
