interface Env {
  DATABASE_URL: string;
  WEBHOOK_SECRET: string;
  GOOGLE_GENERATIVE_AI_API_KEY: string;
  LOOPS_API_KEY: string;
  POLAR_ACCESS_TOKEN: string;
  POLAR_PRICE_STARTER: string;
  POLAR_PRICE_BUSINESS: string;
  POLAR_PRICE_ENTERPRISE: string;
  BETTER_AUTH_SECRET: string;
  BETTER_AUTH_URL: string;
  NEXT_PUBLIC_SOKETI_HOST: string;
  NEXT_PUBLIC_SOKETI_KEY: string;
  SOKETI_SECRET: string;
  SOKETI_APP_ID: string;
  UPLOADTHING_TOKEN: string;
}

const env: Env = {
  DATABASE_URL: process.env.DATABASE_URL!,
  WEBHOOK_SECRET: process.env.WEBHOOK_SECRET!,
  GOOGLE_GENERATIVE_AI_API_KEY: process.env.GOOGLE_GENERATIVE_AI_API_KEY!,
  LOOPS_API_KEY: process.env.LOOPS_API_KEY!,
  POLAR_ACCESS_TOKEN: process.env.POLAR_ACCESS_TOKEN!,
  POLAR_PRICE_STARTER: process.env.POLAR_PRICE_STARTER!,
  POLAR_PRICE_BUSINESS: process.env.POLAR_PRICE_BUSINESS!,
  POLAR_PRICE_ENTERPRISE: process.env.POLAR_PRICE_ENTERPRISE!,
  BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET!,
  BETTER_AUTH_URL: process.env.BETTER_AUTH_URL!,
  NEXT_PUBLIC_SOKETI_HOST: process.env.NEXT_PUBLIC_SOKETI_HOST!,
  NEXT_PUBLIC_SOKETI_KEY: process.env.NEXT_PUBLIC_SOKETI_KEY!,
  SOKETI_SECRET: process.env.SOKETI_SECRET!,
  SOKETI_APP_ID: process.env.SOKETI_APP_ID!,
  UPLOADTHING_TOKEN: process.env.UPLOADTHING_TOKEN!,
};

export default env;
